version: "3.5"
services:
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "gorm_demo"
      POSTGRES_PASSWORD: password
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 8009:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database-data:
